/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan;

/**
 *
 * @author TUF
 */
public class Latihan_4 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan_4
     */
    public Latihan_4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Absen = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        rdb2 = new javax.swing.JRadioButton();
        rdb1 = new javax.swing.JRadioButton();
        cb2 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        cb1 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        buttonGroup0 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Biodata Siswa");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 20, 160, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Hasil");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 260, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 50, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Absen");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 90, 50, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Jurusan");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 130, 80, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Hobi");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 170, 80, 30);

        Absen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbsenActionPerformed(evt);
            }
        });
        jPanel1.add(Absen);
        Absen.setBounds(110, 90, 190, 30);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        jPanel1.add(Nama);
        Nama.setBounds(110, 50, 190, 30);

        rdb2.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup2.add(rdb2);
        rdb2.setText("TKJ");
        rdb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb2ActionPerformed(evt);
            }
        });
        jPanel1.add(rdb2);
        rdb2.setBounds(190, 130, 60, 25);

        rdb1.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup2.add(rdb1);
        rdb1.setText("RPL");
        rdb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb1ActionPerformed(evt);
            }
        });
        jPanel1.add(rdb1);
        rdb1.setBounds(110, 130, 60, 25);

        cb2.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup3.add(cb2);
        cb2.setText("Animator");
        jPanel1.add(cb2);
        cb2.setBounds(110, 200, 100, 25);

        cb4.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup3.add(cb4);
        cb4.setText("Designer");
        jPanel1.add(cb4);
        cb4.setBounds(230, 200, 100, 25);

        cb1.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup3.add(cb1);
        cb1.setText("Programing");
        jPanel1.add(cb1);
        cb1.setBounds(110, 170, 100, 25);

        cb3.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup3.add(cb3);
        cb3.setText("Teknisi");
        jPanel1.add(cb3);
        cb3.setBounds(230, 170, 100, 25);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 230, 79, 25);

        buttonGroup0.setText("Submit");
        buttonGroup0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGroup0ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGroup0);
        buttonGroup0.setBounds(50, 230, 73, 25);

        buttonGroup1.setText("Hapus");
        buttonGroup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGroup1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGroup1);
        buttonGroup1.setBounds(140, 230, 79, 25);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 290, 290, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(385, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbsenActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void rdb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb2ActionPerformed

    private void rdb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb1ActionPerformed

    private void buttonGroup0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGroup0ActionPerformed
        String nama = Nama.getText();
        String absen = Absen.getText();
        String jurusan = null;
        String hobi = "";
        // untuk rd
        if (rdb1.isSelected()) {
            jurusan = "RPL";
        } else if (rdb2.isSelected()) {
            jurusan = "TKJ";
        }
        //untuk checkbox
        if (cb1.isSelected()) {
            hobi += cb1.getText() + ", ";
        }
        if (cb2.isSelected()) {
            hobi += cb2.getText() + ", ";
        }
        if (cb3.isSelected()) {
            hobi += cb3.getText() + ", ";
        }
        if (cb4.isSelected()) {
            hobi += cb4.getText() + ", ";
        }
        TA.setText("Nama siswa \t: " + nama + "\n"
                + "Absen siswa\t: " + absen + "\n"
                + "Jurusan anda\t: " + jurusan + "\n"
                + "Hobi anda  \t: " + hobi);
    }//GEN-LAST:event_buttonGroup0ActionPerformed

    private void buttonGroup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGroup1ActionPerformed
        TA.setText("");
        Nama.setText("");
        Absen.setText("");
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        rdb1.setSelected(false);
        rdb2.setSelected(false);
        cb1.setSelected(false);
        cb2.setSelected(false);
        cb3.setSelected(false);
        cb4.setSelected(false);
    }//GEN-LAST:event_buttonGroup1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextArea TA;
    private javax.swing.JButton buttonGroup0;
    private javax.swing.JButton buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdb1;
    private javax.swing.JRadioButton rdb2;
    // End of variables declaration//GEN-END:variables
}
